=== AlexeyDsov/onphp-framework/meta/dtd/meta.dtd
<!ELEMENT metaconfiguration (classes+, sources*)>

<!ELEMENT classes (class+)>

<!ELEMENT class (implement*, properties*, pattern)>
<!ATTLIST class
		name		ID #REQUIRED
		type		(final|abstract|spooked) #IMPLIED
		extends		CDATA #IMPLIED
		source		CDATA #IMPLIED
>

<!ELEMENT implement EMPTY>
<!ATTLIST implement
		interface	CDATA #REQUIRED
>

<!ELEMENT properties (identifier?, property*)>

<!ELEMENT identifier EMPTY>
<!ATTLIST identifier
		name	CDATA #IMPLIED
		type	CDATA #IMPLIED
		column	CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
		name		CDATA #REQUIRED
		type		CDATA #REQUIRED
		size		CDATA #IMPLIED
		column		CDATA #IMPLIED
		default		CDATA #IMPLIED
		required	(true|false) "false"
		relation	CDATA #IMPLIED
>

<!ELEMENT pattern EMPTY>
<!ATTLIST pattern
		name		(DictionaryClass|AbstractClass|StraightMapping|EnumerationClass|SpookedClass) #REQUIRED
>

<!ELEMENT sources (source+)>

<!ELEMENT source EMPTY>
<!ATTLIST source
		name	CDATA #REQUIRED
		default	(true|false) "false"
>

=== AlexeyDsov/onphp-framework/doc/project.skel/meta/config.xml
<?xml version="1.0"?>
<!DOCTYPE metaconfiguration SYSTEM "meta.dtd">

<!-- $Id$ -->

<metaconfiguration><classes>

	<class name="Administrator" type="final">
		<properties>
			
			<property name="id" type="Integer" required="true" identifier="true" />
			
			<property name="username" type="String" size="64" required="true" />
			<property name="password" type="Password" size="40" required="true" />
			
		</properties>
		
		<pattern name="DictionaryClass" />
	</class>

</classes></metaconfiguration>

=== AlexeyDsov/onphp-framework/test/meta/config.meta.xml
<?xml version="1.0"?>
<!DOCTYPE metaconfiguration SYSTEM "meta.dtd">

<!-- $Id$ -->

<metaconfiguration><classes>

	<class name="Spook" type="spooked">
		<properties>
			<property name="id" type="Integer" required="true" identifier="true" />
		</properties>
		
		<pattern name="SpookedClass" />
	</class>

	<class name="TestCity" type="final">
		<properties>
			
			<property name="id" type="BigInteger" required="true" identifier="true" />
			<property name="name" type="String" size="50" required="true" />
			
		</properties>
		
		<pattern name="DictionaryClass" />
	</class>
	
	<class name="TestUser" type="final">
		<properties>
			
			<property name="id" type="BigInteger" required="true" identifier="true" />
			
			<property name="nickname" type="String" size="255" required="true" />
			<property name="password" type="Password" required="true" />
			
			<property name="lastLogin" type="Timestamp" required="true" />
			<property name="registered" type="Timestamp" required="true" />
			
			<property name="city" type="TestCity" relation="OneToOne" required="true" />
			
			<property name="spook" type="Spook" relation="OneToOne" required="false" />
			
			<property name="firstOptional" type="TestCity" relation="OneToOne" required="false" />
			<property name="secondOptional" type="TestCity" relation="OneToOne" required="false" />
			
		</properties>
		
		<pattern name="StraightMapping" />
	</class>
	
</classes></metaconfiguration>

=== AlexeyDsov/onphp-framework/nsConverter/xml/config.xml
<?xml version="1.0"?>
<!DOCTYPE metaconfiguration SYSTEM "meta.dtd">
<metaconfiguration>

	<classes namespace="Onphp\NsConverter">
		<class name="NsClass">
			<implement interface="\Onphp\NsConverter\NsObject" />
			<properties>
				<property name="name" type="String" size="256" required="true" />
				<property name="namespace" type="String" size="256" required="true" />
				<property name="newNamespace" type="String" size="256" required="true" />
			</properties>
			<pattern name="ValueObject" />
		</class>

		<class name="NsFunction">
			<implement interface="\Onphp\NsConverter\NsObject" />
			<properties>
				<property name="name" type="String" size="256" required="true" />
				<property name="namespace" type="String" size="256" required="true" />
				<property name="newNamespace" type="String" size="256" required="true" />
			</properties>
			<pattern name="ValueObject" />
		</class>

		<class name="NsConstant">
			<properties>
				<property name="name" type="String" size="256" required="true" />
			</properties>
			<pattern name="ValueObject" />
		</class>
	</classes>

	<sources>
		<source name="con" default="false"/>
	</sources>
</metaconfiguration>
